### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mick-t** [mej/nhc#109]
Hi,

Are there any plans to drop a new release of NHC? The current version `LBNL NHC version 1.4.2` is 6 years and there appears to be a lot of changes in the meantime.

Thanks
--Mick

**Comment by rezib** [comment]
Note to those who are interested that there is already #85 about this.

**Comment by mick-t** [comment]
There sure is, but that issue doesn't look like it has had any TLC in a while. If the project needs help packaging, I can help and have build my own packages for use with the cluster I maintain.

**Comment by mej** [comment]
If you have commented on #85 or #109, please check your e-mail.  If you don't have a relevant e-mail from me, I'd ask that you contact me privately (via e-mail or on GH) so I can correct the error.

😃

**Comment by mick-t** [comment]
New release is in progress. Closing issue.
