### ISSUE TITLE
nhc-wrapper error

### ISSUE THREAD

**Issue by jv2575** [mej/nhc#18]
Hello,
The following error appears to be reoccurring:

/usr/sbin/nhc-wrapper: line 199: 25013 Killed                  "$SUBPROG" "${ARGLIST[@]}" &>"$OUTFILE"

Can you please help me to better understand this error and resolve it?

**Comment by mej** [comment]
This isn't an error, per se.  This just means that the subprogram (typically `nhc`) was terminated by signal 9, `SIGKILL`.  Further details may be available in the output file, but it's hard to say what might've caused the subprogram to die.  In the case of NHC, the most likely source of that signal is either the watchdog timer or a system shutdown.

Does that help at all?

**Comment by mej** [comment]
No response.  Closing issue.
