### ISSUE TITLE
Problem with Slurm node state check?

### ISSUE THREAD

**Issue by verdurin** [mej/nhc#19]
I have a node that was being used for testing and now I want to bring it back into service.

Looking at the `NHC` logs, the Slurm node state check is failing both to mark the node offline and mark it online, when appropriate:

```
20160704 14:18:00 /usr/libexec/nhc/node-mark-offline hmem000. check_fs_mount:  /camp not mounted
/usr/libexec/nhc/node-mark-offline:  Not sure how to handle node state "" on hmem000.
20160704 14:23:03 [slurm] /usr/libexec/nhc/node-mark-online hmem000.
/usr/libexec/nhc/node-mark-online:  Not sure how to handle node state "" on hmem000.
/usr/libexec/nhc/node-mark-online:  Skipping  node hmem000. ( )
```

**Comment by mej** [comment]
This is happening because NHC is unable to read the node status from SLURM.  The command it uses to do this can be found in [`/usr/libexec/nhc/node-mark-offline` at line `61`](https://github.com/mej/nhc/blob/master/helpers/node-mark-offline#L61):
``` bash
  $SLURM_SINFO -o '%t %E' -hn $HOSTNAME
```
What do you get when you run `sinfo -o '%t %E' -hn hmem000` by hand?  Is there perhaps some mismatch between the canonical hostname (i.e., the value of `$(hostname)` on the node) and the nodename in SLURM?

**Comment by verdurin** [comment]
When I run that from the SLURM controller, I see this:

```
down Node unexpectedly rebooted
```

whereas when I run it from the node itself, there's no output, with the FQDN (which is what NHC is using), but the same as above if I use `hmem000`, which is the SLURM `NodeName`.

**Comment by verdurin** [comment]
I've tried adding `* || HOSTNAME = "$HOSTNAME_S"` at the top of `nhc.conf`, but that produces this error:

```
20160705 22:14:15 /usr/libexec/nhc/node-mark-offline hmem000.camp.thecrick.org Check HOSTNAME = "$HOSTNAME_S" returned 127
/usr/libexec/nhc/node-mark-offline:  Not sure how to handle node state "" on hmem000.camp.thecrick.org
/usr/sbin/nhc: line 587: HOSTNAME: command not found
Node Health Check failed.  Check HOSTNAME = "$HOSTNAME_S" returned 127
ERROR:  nhc:  Health check failed:  Check HOSTNAME = "$HOSTNAME_S" returned 127
```

**Comment by mej** [comment]
This is shell code, so spaces around the equals sign are prohibited.  Try removing them. :-)

``` bash
 * || HOSTNAME="$HOSTNAME_S"
```

But for that variable in particular, you'l likely want to do that either in `/etc/sysconfig/nhc` or on the command line (e.g., `nhc HOSTNAME=$(hostname -s)`) instead.

**Comment by mej** [comment]
Please do note that NHC **requires** that the canonical name (i.e., `$(hostname)` and `$HOSTNAME`, the latter being derived from `/proc/sys/kernel/hostname`) be an exact match to the name used by the Resource Manager in order for manipulation of the node's RM state to function properly.  Some RMs (like TORQUE) enforce this by default, but others (like SLURM) don't.  For those that don't, the onus is on the admin to either make sure they match or configure NHC's `$HOSTNAME` variable appropriately prior to, at minimum, attempting to online/offline the node.  This is noted in the documentation under [TORQUE Integration](https://github.com/mej/nhc#torque-integration).

I'm going to close the issue assuming that this has resolved your situation, but please feel free to reopen if not!  :-)
