### ISSUE TITLE
check_ps_userproc_lineage prints with UID instead of username

### ISSUE THREAD

**Issue by treydock** [mej/nhc#28]
I currently have check_ps_userproc_lineage set to log and syslog and noticed that the log messages all use a user's UID instead of the username.  My read of the code is that username is supposed to be what's printed.  Seems that check_ps_unauth_users is correctly using username.

Example from `nhc -l- -v`:

```
Running check:  "check_ps_userproc_lineage log syslog"
check_ps_userproc_lineage:  20705's "sh" process is rogue. (PID 27519)
```

Example from syslog:

```
Mar  3 16:28:02 o0199 nhc[52778]: check_ps_userproc_lineage:  20705's "sh" process is rogue. (PID 27519)
```

**Comment by mej** [comment]
Hmmm, looks like some outdated code that never got updated.

In `check_ps_userproc_lineage()`, there's a line (around [704](https://github.com/mej/nhc/blob/glob-disable/scripts/lbnl_ps.nhc#L704) or [705](https://github.com/mej/nhc/blob/master/scripts/lbnl_ps.nhc#L705), depending on your version) that looks like this:

``` bash
    THIS_USER="${PWUID_USER[$THIS_UID]:-$THIS_UID}"
```

Try changing it to read

``` bash
    THIS_USER="${PS_USER[$THIS_PID]:-$THIS_UID}"
```

instead.  Does that work better?
