### ISSUE TITLE
lbnl_file.nhc...../scripts/lbnl_file.nhc: line 83: /dev/fd/63: No such file or directory

### ISSUE THREAD

**Issue by lipixx** [mej/nhc#31]
When issuing a make test in git (9ac3a1a34caca5ea398408a6dfdaf6b48e3e86fe) version it throws an error. This make impossible to build the RPMs:
```
[lipi@llagosti src]$ git clone https://github.com/mej/nhc.git
..
[lipi@llagosti src]$ cd nhc/
..
[lipi@llagosti nhc]$ ./autogen.sh 
..
[lipi@llagosti nhc]$ make test
make -C test test
make[1]: Entering directory '/home/lipi/src/nhc/test'
Running unit tests for NHC:
nhcmain_init_env...ok 6/6
nhcmain_help...ok 8/8
nhcmain_parse_cmdline...ok 16/16
nhcmain_finalize_env...ok 14/14
nhcmain_check_conffile...ok 1/1
nhcmain_load_scripts...ok 6/6
nhcmain_set_watchdog...ok 1/1
nhcmain_watchdog_timer...ok 3/3
nhcmain_run_checks...ok 2/2
common.nhc...ok 108/108
lbnl_cmd.nhc...ok 13/13
lbnl_dmi.nhc...ok 45/45
lbnl_file.nhc...../scripts/lbnl_file.nhc: line 83: /dev/fd/63: No such file or directory
failed 4/71
TEST FAILED:  Single regexp match success:  Got "1" but expected "0"
Makefile:391: recipe for target 'test' failed
make[1]: *** [test] Error 255
make[1]: Leaving directory '/home/lipi/src/nhc/test'
Makefile:925: recipe for target 'test' failed
make: *** [test] Error 2
```

It is tested in Fedora 25 and SLES 12 SP1.

**Comment by mej** [comment]
That would seem to indicate that your version of `bash` isn't correctly supporting the process substitution construct (`<(...)`) required for NHC's file check tests to work correctly.

If your version of `rpmbuild` supports it, you should be able to skip the `%check` section of the spec file by executing `rpmbuild --nocheck`

**Comment by lipixx** [comment]
I am still investigating the problem but it seems that the created fd is destroyed once the process is ended:

Look at this test case:

Define a variable with values:
```
[lipi@llagosti test]$ values="1,2,3,4,5"
[lipi@llagosti test]$ echo $values
1,2,3,4,5
```

Do a process substitution and store file descriptor:
```
[lipi@llagosti test]$ filedata=<(echo $values)
[lipi@llagosti test]$ echo $filedata
/dev/fd/63
```

Try to count it:
```
[lipi@llagosti test]$ wc <(cat $filedata)
cat: /dev/fd/63: No such file or directory
      0       0       0 /dev/fd/63
```


If, instead, I directly pass the process substitution result to wc, it works:
```
[lipi@llagosti test]$ wc <(echo $values)
      1       1      10 /dev/fd/63
```


The NHC code does exactly what happens when it is failing:
nhc/test/test_lbnl_file.nhc defines a filedata like this:

`FILEDATA=$'line1\nline2\nline3\nline4\nline5\nline6\n'`

then the fd is stored this way:

`FILEDATA_FILE=<(echo "$FILEDATA")`

then the "check_file_contents $FILEDATA_FILE '/line3/'" function is called, referring to scripts/lbnl_file.nhc and then passed to a while construct like this:
`done <"$FILENAME"`

Here is where it is failing, the fd isn't there since the <() was ended time ago.


How can I be sure that it is a bash problem?


```
[lipi@llagosti test]$ bash --version
GNU bash, version 4.3.43(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

```
