### ISSUE TITLE
Slurm node state "resv" not understood by node-mark-online

### ISSUE THREAD

**Issue by OleHolmNielsen** [mej/nhc#41]
We had a node with a Slurm reservation so that it's state was "reserved". This state is not understood by node-mark-online:

20170711 16:05:45 [slurm] /usr/libexec/nhc/node-mark-online h001
/usr/libexec/nhc/node-mark-online:  Not sure how to handle node state "resv" on h001
/usr/libexec/nhc/node-mark-online:  Skipping resv node h001 (none )

It seems to me that this could be solved by changing /usr/libexec/nhc/node-mark-online
77c77
<         alloc*|comp*|idle*|mix*|resume*|undrain*|resv*)
---
>         alloc*|comp*|idle*|mix*|resume*|undrain*)

**Comment by mej** [comment]
This is already fixed in 8aa5575dd6 which closed #17.  The fix will be in 1.4.3 when released.
