### ISSUE TITLE
check_ps_userproc_lineage misses users whos UID == MAX_SYS_UID

### ISSUE THREAD

**Issue by SMark-Black** [mej/nhc#50]
My UID is 1000 which happens to correspond to the MAX_SYS_UID value.  As a result my processes are never flagged as rogue processes.
Diff to fix it is:

```
diff --git a/scripts/lbnl_ps.nhc b/scripts/lbnl_ps.nhc
index 1c894cb..cfffbed 100644
--- a/scripts/lbnl_ps.nhc
+++ b/scripts/lbnl_ps.nhc
@@ -674,7 +674,7 @@ function check_ps_unauth_users() {
                 log )    log "$UNAUTH_MSG" ;;
                 syslog ) syslog "$UNAUTH_MSG" ;;
                 die )    die 1 "$UNAUTH_MSG" ; return 1 ;;
-                kill )   [[ ${THIS_UID:-0} -gt $MAX_SYS_UID ]] && kill -9 $THIS_PID ;;
+                kill )   [[ ${THIS_UID:-0} -ge $MAX_SYS_UID ]] && kill -9 $THIS_PID ;;
                 ignore ) break ;;
             esac
         done
@@ -704,7 +704,7 @@ function check_ps_userproc_lineage() {
         THIS_UID="${PS_UID[$THIS_PID]}"
         THIS_USER="${PS_USER[$THIS_PID]:-${PWUID_USER[$THIS_UID]:-$THIS_UID}}"
         THIS_CMD="${PS_ARGS[$THIS_PID]/% *}"
-        if [[ ${THIS_UID:-0} -le $MAX_SYS_UID ]]; then
+        if [[ ${THIS_UID:-0} -lt $MAX_SYS_UID ]]; then
             continue
         fi
         if mcheck "${NHC_AUTH_USERS}" "/(^|[^A-Za-z0-9])$THIS_USER(\$|[^A-Za-z0-9])/" ; then
@@ -723,7 +723,7 @@ function check_ps_userproc_lineage() {
                 log )    log "$UNAUTH_MSG" ;;
                 syslog ) syslog "$UNAUTH_MSG" ;;
                 die )    die 1 "$UNAUTH_MSG" ; return 1 ;;
-                kill )   [[ ${THIS_UID:-0} -gt $MAX_SYS_UID ]] && kill -9 $THIS_PID ;;
+                kill )   [[ ${THIS_UID:-0} -ge $MAX_SYS_UID ]] && kill -9 $THIS_PID ;;
                 ignore ) break ;;
             esac
         done

```

**Comment by mej** [comment]
Are you sure you don't want to submit that as a Pull Request so you get credit for the commit? :-)

**Comment by SMark-Black** [comment]
Love to, but get:   
$ git push origin pull-request-fix-50 -v
Pushing to git@github.com:mej/nhc.git
ERROR: Permission to mej/nhc.git denied to SMark-Black.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by mej** [comment]
You'll have to "Fork" first using the Fork button in the upper right.  That'll create an "nhc" repository on your account.  Then you can commit your fix to a branch in that repo and push it up to GitHub.  Once the commit with the fix is in your tree, you can submit a PR asking me to merge it into mine.

Detailed instructions can be found [here](https://help.github.com/articles/creating-a-pull-request-from-a-fork/).  Hope that helps!

**Comment by SMark-Black** [comment]
Okay did it.  Also added minor change to support LSF better.

Should the nhc-genconf script also generate checks for the resource managers?
