### ISSUE TITLE
Detached Mode error

### ISSUE THREAD

**Issue by hwj0303** [mej/nhc#59]
When the detached mode is set, the log is displayed “ERROR:  nhc:  Unable to write to "/var/run/nhc/nhc.status" -- is /var/run/nhc read-only?”.The /var/run/nhc is drwxr-xr-x.

**Comment by mej** [comment]
It's not just a question of permissions but also of mount options and UID.  Make sure NHC is running as `root` and that the filesystem containing `/var/run/nhc` is not mounted read-only.  You can also try running NHC under `strace` to see the exact error that's occurring.  In any event, this is a local issue, not an upstream/code issue.

**Comment by hwj0303** [comment]
I think the /usr/sbin/nhc has a question.
I solved this problem by change the /use/sbin/nhc file :
if [[ -w "$RESULTFILE" ]]; then
to be :
if [[ ! -f "$RESULTFILE" ]] || [[ -w "$RESULTFILE" ]]; then

the question is due to $RESULTFILE is not created and it will go to the else function.
