### ISSUE TITLE
e-mail address nhc@lbnl.gov does not work

### ISSUE THREAD

**Issue by martbhell** [mej/nhc#7]
The address is mentioned in several places in the README.

I got this from the Mail Delivery Subsystem:

<pre>
From: Mail Delivery Subsystem <mailer-daemon@googlemail.com>
To: johan.guldmyr@domain
X-Failed-Recipients: nhc@lbl.gov
Subject: Delivery Status Notification (Failure)
Message-ID: <001a1145b24a6a7e63052a4b8c8c@google.com>
Date: Wed, 27 Jan 2016 07:14:10 +0000
Content-Type: text/plain; charset=UTF-8
X-Bayes-Prob: 0.0001 (Score 0, tokens from: 01_Tag_Only, default, @@RPTN)
X-Spam-Score: 0.00 () [Tag at 5.00] FREEMAIL_FROM:0.001
X-CanIt-Geo: ip=2607:f8b0:400e:c00::242; country=US; region=Oregon; city=The Dalles; latitude=45.5447; longitude=-121.1543; http://maps.google.com/maps?q=45.5447,-121.1543&z=6
X-CanItPRO-Stream: 01_Tag_Only (inherits from default)
X-Canit-Stats-ID: 01QaTwhro - d13946051ad9
X-Scanned-By: CanIt (www . roaringpenguin . com)

Hello johan.guldmyr@domain

We're writing to let you know that the group you tried to contact (nhc) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:

 * You might have spelled or formatted the group name incorrectly.
 * The owner of the group may have removed this group.
 * You may need to join the group before receiving permission to post.
 * This group may not be open to posting.

If you have questions related to this or any other Google Group, visit the Help Center at https://support.google.com/a/lbl.gov/bin/topic.py?topic=25838.

Thanks,

lbl.gov admins

</pre>

**Comment by mej** [comment]
I certainly agree that's not as helpful a message as it could be, but what it's trying to tell you is that you need to join the list before being able to post to it.  Send a message to nhc+subscribe@lbl.gov or visit https://groups.google.com/a/lbl.gov/forum/#!forum/nhc to subscribe.

**Comment by mej** [comment]
Group settings for `nhc@lbl.gov` have been changed to allow posts from non-members to be moderated rather than bounced, so this should be "fixed" now.

**Comment by mej** [comment]
For future reference, I have changed the group config such that subscription is no longer required to post to nhc@lbl.gov.  It's still required for the -devel list, though.
