### ISSUE TITLE
Not able to provide a custom configuration directory for nhc-genconf. It always picks /etc/nhc

### ISSUE THREAD

**Issue by naureensaba** [mej/nhc#78]
LBNL NHC
The nhc utility has an option to specify the custom configuration directory using the -D option, in order to load the scripts from the custom directory.

Whereas the nhc-genconf utility doesn't have this option. It always loads the '*.nhc' scripts from the /etc/nhc/scripts directory.

If I have configured nhc in a way where I have all my '*.nhc' scripts in the /opt/clustertest/nhc/etc/nhc/scripts directory.

nhc-genconf has the following option:
-c Write config to (default: /etc/nhc/nhc.conf.auto)

But I am not able to generate the configuration file using the -c option, as it is expecting the '*.nhc ' scripts to be in the /etc/nhc/scripts directory.

It always gives me the following error:
/opt/clustertest/nhc/sbin/nhc-genconf: line 330: nhc_common_unparse_size: command not found
/opt/clustertest/nhc/sbin/nhc-genconf: line 334: nhc_common_unparse_size: command not found

**Comment by mej** [comment]
Yes, I think adding support for `-D` and an alternate prefix/path would be a useful addition!

Would you like to take a crack at such a feature and submit a PR?

**Comment by naureensaba** [comment]
Thank you for your reply.

I will raise a PR soon :-)

**Comment by mej** [comment]
This issue was resolved by #79 via merge commit 9095c63.  Closing this Issue.  Thanks again for your contributions!
