### ISSUE TITLE
error in nhc_common_parse_passwd_entry with unsafe array splitting

### ISSUE THREAD

**Issue by paulraines68** [mej/nhc#93]
I was having mysterious failures of nhc with really wierd entries in nhc.log like:

`/etc/nhc/scripts/common.nhc: line 381: slurmd.log-20201001: syntax error: invalid arithmetic operator (error token is ".log-20201001")`

This was only when nhc was run from SLURM and not directly.

I tracked it down to the user munge in /etc/passwd which is defined as:

`munge:*:485:485:Runs Uid 'N' Gid Emporium:/var/run/munge:/sbin/nologin`

Note the asterisk in the password field and single quotes in the GECOS

I modified nhc_common_parse_passwd_entry like so to narrow things down

```
function nhc_common_parse_passwd_entry() {
    local IFS=':'
    local PASSWD_ENTRY="$1"
    local UID_VAR="$2"
    local THIS_UID
    local -a LINE

log "PASSWD LINE: $PASSWD_ENTRY  [ $UID_VAR ]"

    LINE=( $PASSWD_ENTRY )
    THIS_UID=${LINE[2]}
log "PASSWD THIS_UID: $THIS_UID"
    PWDATA_UIDS[${#PWDATA_UIDS[*]}]=$THIS_UID
log "PASSWD USER: ${LINE[0]}"
    PWUID_USER[$THIS_UID]="${LINE[0]}"
log "PASSWD GID: ${LINE[3]}"
    PWUID_GID[$THIS_UID]="${LINE[3]}"
log "PASSWD GECOS: ${LINE[4]}"
    PWUID_GECOS[$THIS_UID]="${LINE[4]}"
log "PASSWD HOME: ${LINE[5]}"
    PWUID_HOME[$THIS_UID]="${LINE[5]}"
log "PASSWD SHELL: ${LINE[6]}"
    PWUID_SHELL[$THIS_UID]="${LINE[6]}"
```

And in the the log when it gets to munge I see:

```
PASSWD LINE: munge:*:485:485:Runs Uid 'N' Gid Emporium:/var/run/munge:/sbin/nologin  [  ]
PASSWD THIS_UID: slurmd.log-20201001
PASSWD USER: munge
/etc/nhc/scripts/common.nhc: line 385: slurmd.log-20201001: syntax error: invalid arithmetic operator (error token is ".log-20201001")
```

The issue is the line

`    LINE=( $PASSWD_ENTRY )`

is unsafe if the line has special chars like the asterisk or single quotes.  The asterisk is what is bringing in that slurmd.log-20201001 entry.  Depending on the names of the files in the current directory where nhc is run from this could just fail silently without any logged error even though the passwd is mis-parsed.

Adding the lines

```
local -
set -o noglob
```

at the top of the function fixes the asterisk thing.  Not sure if there are other special chars to worry about.

**Comment by dgtim** [comment]
Here we noticed the same behavior.

**Comment by dgtim** [comment]
Special character in the passwd entry:
```
$ getent passwd someuser
someuser:*:123456:123456:Some User:/home/someuser:/bin/bash
$ IFS=: LINE=( $(getent passwd someuser) ); echo ${LINE[1]}
.. list a file in the directory I run the command
```

**Comment by dgtim** [comment]
```
function nhc_common_parse_passwd_entry() {
    set -f
...
    set +f
}
```

**Comment by mej** [comment]
As I already mentioned in #97, I'm reasonably confident that this has already been corrected.

In the interest of not overly confusing myself in my old age :rofl:, I'm going to close this Issue in favor of continuing the overall conversation in #97.
