### ISSUE TITLE
Health check failed:  Script timed out while executing "check_ps_daemon sshd root"

### ISSUE THREAD

**Issue by mick-t** [mej/nhc#95]
Hi,

On a number of nodes we're seeing the following:

`Health check failed:  Script timed out while executing "check_ps_daemon sshd root"`

It causes our Slurm nodes to drain and then resume when the next check runs. Any suggestions on how to debug this or workaround this? Is there any way to configure the check to time out? I don't see any excessive load on the systems when this happens, it's possible that the script it timing out due to a large number of processes running, or because NFS mount is hung for a short period of time.

Kind regards!
--Mick

**Comment by mej** [comment]
My recommendation would be to run NHC is either debug (`-d`) mode or trace (`-x`) mode.  Or both.  Either one will display the entire set of processes NHC reads in and all the fields for each process.  You should then be able to discern what's happening and where it's getting hung up.

There are 2 timeout values NHC uses.  The global timeout governs how long the watchdog timer process will wait for NHC to finish before it terminates the primary `nhc` process; you set this value using the `TIMEOUT` variable or the `-t` CLI option.  You can find more info about that here:  https://github.com/mej/nhc/#configuration

Additionally, some checks -- in particular, the built-in ones that execute arbitrary external commands -- have their own timeout for specifically that operation.  If that single external command does not return within the specified timeout, NHC will kill it and report the failure.  You can read through the documentation for one such check, `check_cmd_output()`, at https://github.com/mej/nhc/#check_cmd_output

The default value for `TIMEOUT` is 30 (seconds); the default timeout in `check_cmd_output()` and friends is 5 (also in seconds).

The message you quoted is the former case, so you can easily try some experiments by adding the `-t <seconds>` argument to your invocation of `nhc` along with the `-d` and/or `-x` flags recommended above.

Hopefully some combination of these will get you headed in the right direction!

**Comment by mick-t** [comment]
Thanks for the advice @mej .
